const actionTypes = {
  LOGIN: 'LOGIN',

  GET_PRODUCTS_STARTED: 'GET_PRODUCTS_STARTED',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED',

  ADD_PRODUCTS_STARTED: 'ADD_PRODUCTS_STARTED',
  ADD_PRODUCTS_SUCCESS: 'ADD_PRODUCTS_SUCCESS',
  ADD_PRODUCTS_FAILED: 'ADD_PRODUCTS_FAILED',

  DELETE_PRODUCTS_STARTED: 'DELETE_PRODUCTS_STARTED',
  DELETE_PRODUCTS_SUCCESS: 'DELETE_PRODUCTS_SUCCESS',
  DELETE_PRODUCTS_FAILED: 'DELETE_PRODUCTS_FAILED',

  GET_AUTH_STARTED: 'GET_AUTH_STARTED',
  GET_AUTH_SUCCESS: 'GET_AUTH_SUCCESS',
  GET_AUTH_FAILED: 'GET_AUTH_FAILED',
  SET_AUTH_LOGGED: 'SET_AUTH_LOGGED',

  PUT_AUTH_STARTED: 'PUT_AUTH_STARTED',
  PUT_AUTH_SUCCESS: 'PUT_AUTH_SUCCESS',
  PUT_AUTH_FAILED: 'PUT_AUTH_FAILED',

  GET_ALL_USER_STARTED: 'GET_ALL_USER_STARTED',
  GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
  GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',

  LOG_OUT: 'LOG_OUT',

  VALIDATE_ME_STARTED: 'VALIDATE_ME_STARTED',
  VALIDATE_ME_SUCCESS: 'VALIDATE_ME_SUCCESS',
  VALIDATE_ME_FAILED: 'VALIDATE_ME_FAILED',

  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY_CART: 'UPDATE_QUANTITY_CART',

  ADD_ORDERS_STARTED: 'ADD_ORDERS_STARTED',
  ADD_ORDERS_SUCCESS: 'ADD_ORDERS_SUCCESS',
  ADD_ORDERS_FAILED: 'ADD_ORDERS_FAILED',

  ADD_ADMIN_ORDERS_STARTED: 'ADD_ADMIN_ORDERS_STARTED',
  ADD_ADMIN_ORDERS_SUCCESS: 'ADD_ADMIN_ORDERS_SUCCESS',
  ADD_ADMIN_ORDERS_FAILED: 'ADD_ADMIN_ORDERS_FAILED',

  GET_ORDERS_STARTED: 'GET_ORDERS_STARTED',
  GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FAILED: 'GET_ORDERS_FAILED',
};

export default actionTypes;
