const actionTypes = {
  LOGIN: 'LOGIN',

  GET_PRODUCTS_STARTED: 'GET_PRODUCTS_STARTED',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED',

  GET_AUTH_STARTED: 'GET_AUTH_STARTED',
  GET_AUTH_SUCCESS: 'GET_AUTH_SUCCESS',
  GET_AUTH_FAILED: 'GET_AUTH_FAILED',
  SET_AUTH_LOGGED: 'SET_AUTH_LOGGED',

  PUT_AUTH_STARTED: 'PUT_AUTH_STARTED',
  PUT_AUTH_SUCCESS: 'PUT_AUTH_SUCCESS',
  PUT_AUTH_FAILED: 'PUT_AUTH_FAILED',

  LOG_OUT: 'LOG_OUT',

  VALIDATE_ME_STARTED: 'VALIDATE_ME_STARTED',
  VALIDATE_ME_SUCCESS: 'VALIDATE_ME_SUCCESS',
  VALIDATE_ME_FAILED: 'VALIDATE_ME_FAILED',

  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY_CART: 'UPDATE_QUANTITY_CART',

  ADD_ORDERS: 'ADD_ORDERS',
  SET_ORDERS_PAYMENT: 'SET_ORDERS_PAYMENT',

};

export default actionTypes;
