const actionTypes = {
  LOGIN: 'LOGIN',

  GET_PRODUCTS_STARTED: 'GET_PRODUCTS_STARTED',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED',

  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_QUANTITY_CART: 'UPDATE_QUANTITY_CART',
};

export default actionTypes;
