import Head from 'next/head';
import { Card, Layout } from '../containers';
import PRODUCT from './api/Products.json';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>MBK: Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="shop">
        <div className="Shop__tittle">
          <h2>Products</h2>
          <p>Order it for you or for your beloved ones </p>
        </div>

        <div className="Shop__products">
          {
            PRODUCT.map((item) => (
              <Card key={item.id} title={item.name} imageAlt={item.name} imageSrc={item.img} path={`/Products/${item.id}`} price={item.price} />
            ))
          }
        </div>
      </div>
      <style jsx>
        {`
          .shop {
            display: flex;
            flex-direction: column;
            align-items: center;
          }
          .Shop__tittle {
            text-align: center;
          }
          .Shop__products {
            margin-top: 30px;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-wrap: wrap;
          }
      `}
      </style>
    </Layout>
  );
}
