import {
  GET_PRODUCTS_ACTION,
  ADD_PRODUCTS_ACTION,
  DELETE_PRODUCTS_ACTION,
  GET_SINGLE_PRODUCTS_ACTION,
} from './products';
import {
  ADD_TO_CART_ACTION,
  REMOVE_FROM_CART_ACTION,
  UPDATE_CART,
  UPDATE_QUANTITY_CART,
} from './carts';
import { ADD_ORDERS_ACTION, GET_ORDERS_ACTION, ADD_ADMIN_ORDERS_ACTION , GET_ALL_ORDERS_ACTION} from './orders';
import {
  PUT_AUTH_ACTION,
  GET_AUTH_ACTION,
  VALIDATE_ME_ACTION,
  LOG_OUT_ACTION,
} from './auth';

export {
  GET_SINGLE_PRODUCTS_ACTION,
  GET_PRODUCTS_ACTION,
  ADD_PRODUCTS_ACTION,
  DELETE_PRODUCTS_ACTION,
  ADD_TO_CART_ACTION,
  REMOVE_FROM_CART_ACTION,
  UPDATE_CART,
  UPDATE_QUANTITY_CART,
  ADD_ORDERS_ACTION,
  GET_ORDERS_ACTION,
  PUT_AUTH_ACTION,
  GET_AUTH_ACTION,
  VALIDATE_ME_ACTION,
  LOG_OUT_ACTION,
  ADD_ADMIN_ORDERS_ACTION,
  GET_ALL_ORDERS_ACTION,
};
